-
  name: k8sapp
  hosts: all
  become: yes

  vars:
    k8sapppath: ~/k8sapp
    DIC1:
      - CLI1: client-dev
        PORTINFO:
          - PORTA: '3202'
            TARGETPORTA: '3002'
            PORTNA: '30002'
      - CLI1: client-test
        PORTINFO:
          - PORTA: '3203'
            TARGETPORTA: '3002'
            PORTNA: '30003'
      - CLI1: client-prod
        PORTINFO:
          - PORTA: '3204'
            TARGETPORTA: '3002'
            PORTNA: '30004'

  tasks:
    - name: Creates directory "{{k8sapppath}}"
      file:
        path: "{{k8sapppath}}"
        state: directory

    - copy:
        src: /home/vagrant/ansible/maj_k8sfile.yml
        dest: /home/vagrant/majk8sfile.yml
    - copy:
        src: /home/vagrant/ansible/maj_svck8sfile.yml
        dest: /home/vagrant/majsvck8sfile.yml

    - include_tasks: /home/vagrant/ansible/maj_k8sfile.yml
      vars:
        CLIENTNAME: "{{ item.0.CLI1 }}"
      with_subelements:
        - "{{DIC1}}"
        - PORTINFO
    - include_tasks: /home/vagrant/ansible/maj_svck8sfile.yml
      vars:
        CLIENTNAME: "{{ item.0.CLI1 }}"
        PORT1: "{{ item.1.PORTA }}"
        TARGETPORT: "{{ item.1.TARGETPORTA }}"
        PORTN: "{{ item.1.PORTNA }}"
      with_subelements:
        - "{{DIC1}}"
        - PORTINFO

    - name: nettoyage
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /home/vagrant/majsvck8sfile.yml
        - /home/vagrant/majk8sfile.yml
