-
  name: k8sapp
  hosts: all
  become: yes

  vars:
    img1: gb0001/apptpjuin:latest

  tasks:
    - name: Install pip
      tags: install_pip
      apt:
        name: python3-pip
        state: present
    - name: Install python modules openshift
      tags: install_python_modules_openshift
      pip:
        name: "{{item.name}}"
        executable: pip3
        state: present
      with_items:
        - { name: openshift }
    - name: Create Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "client-{{item.name}}"
            namespace: ns-app-{{item.name}}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "client-{{item.name}}"
            template:
              metadata:
                labels:
                  app: "client-{{item.name}}"
              spec:
                containers:
                - name: "client-{{item.name}}"
                  image: "{{img1}}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - protocol: TCP
                    targetPort: "{{item.targetportn}}"
                    name: "port-{{item.targetportn}}-tcp"
                    port: "{{item.portn}}"
      with_items:
        - { name: dev , targetportn: 3002 , portn: 30002}
        - { name: test , targetportn: 3003 , portn: 30003}
        - { name: prod , targetportn: 3004 , portn: 30004}

    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "client-{{item.name}}"
            namespace: ns-app-{{item.name}}
          spec:
            type: NodePort
            ports:
            - port: "{{item.portn}}"
              targetPort: "{{item.targetportn}}"
            selector:
              app: "{{item.name}}"
      with_items:
        - { name: dev , targetportn: 3002 , portn: 30002}
        - { name: test , targetportn: 3003 , portn: 30003}
        - { name: prod , targetportn: 3004 , portn: 30004}