 pipeline {
    environment {
        registry = "gb0001/apptpjuin"
        registryCredential = 'docker'
        dockerImage = ''
    }


    agent any
    stages {
        stage('clone source') {
            steps {
                sh 'rm -rf tp_juin_ci-cd'
                sh 'git clone https://github.com/arnauddegez/tp_juin_ci-cd.git'
            }
        }

        stage('build') {
            steps {
                sh 'cd ./tp_juin_ci-cd/docker && docker build -t gb0001/apptpjuin .'
               
            }
        }

        stage('run') {
            steps {
                
                sh 'docker run -d --name apptp -p 3002:3002 --rm gb0001/apptpjuin'
            }
        }

        stage('test'){
            steps {
                sh 'sleep 15s'
                sh 'curl http://192.168.40.11:3002'
                
            }
        }
        stage('push Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) { 
                        sh 'docker push gb0001/apptpjuin'
                       
                    }
                }
            }
        }

        stage('deploy') {
            steps {
                sh 'ansible-playbook -i /home/vagrant/ansible/hosts /home/vagrant/ansible/playbook.yml'
            }
        }

    }
}
